---
title: "Curriculum Vitae"
output:
  html_document:
    css: style2.css
  pdf_document: default
---

# Willem W.A. Sleegers

Assistant professor in Social Psychology

[E-mail](w.w.a.sleegers@uvt.nl)
|
[Google Scholar](https://scholar.google.nl/citations?user=EgqxL0MAAAAJ&hl=en)
|
[Github](http://github.com/willemsleegers)
|
[Twitter](http://twitter.com/willemsleegers)

## Currently

I'm an Assistant Professor in the Social Psychology department of [Tilburg University](https://www.tilburguniversity.edu). Here I perform research on the topic of false beliefs, using experimental techniques, physiological tools, and big data. I also teach several courses related to social psychology and supervise students. 

## Employment

### Academic
- `2016-2017` Assistant Professor in social psychology at Tilburg University, performing research largely on the topic of false beliefs.
- `2012-2016` Graduate student on the topic of physiological arousal in meaning maintenance.
- `2011-2012` Student assistant during my Psychology BSc at Nijmegen University.

### Non-academic
- `2012-2013` Programmer of experimental tasks for FrieslandCampina.
- `2007-2010` Media analyst for Report International.

## Education

### Degrees

- `2012-2016` Graduate student at Tilburg University supervised by dr. Ilja van Beest and dr. Travis Proulx.
- `2012-2016` Student member of the Kurt Lewin Institute.
- `2010-2012` Research Master Behavioural Science at Nijmegen University *Degree awarded cum laude*
- `2010-2012` Expert track in data-analysis (part of the Research Master Behavioural Science)
- `2007-2010` Psychology Bsc. at Nijmegen University *Degree awarded cum laude.*
- `2007-2010` Honours Program of Psychology at Nijmegen University

## Publications

Sleegers, W. W. A., Proulx, T., & van Beest, I. (2017). Assimilation and arousal: Pupillary response to error feedback about misconceptions. Manuscript submitted for publication.

Proulx, T., Sleegers, W.W.A., & Tritt, S. (2017) The expectancy bias: Expectancy-violating faces evoke earlier pupillary dilation than neutral or negative faces. In press.

Sleegers, W. W. A., Proulx, T., & van Beest, I. (2016). The social pain of Cyberball: Decreased pupillary reactivity to exclusion cues. Journal of Experimental Social Psychology, 69, 187–200. https://doi.org/10.1016/j.jesp.2016.08.004

Sleegers, W. W. A., Proulx, T., & van Beest, I. (2015). Extremism reduces conflict arousal and increases values affirmation in response to meaning violations. Biological Psychology, 108, 126–131. https://doi.org/10.1016/j.biopsycho.2015.03.012

Sleegers, W. W. A., & Proulx, T. (2015). The comfort of approach: Self-soothing effects of behavioral approach in response to meaning violations. Frontiers in Psychology, 5, 1–10. https://doi.org/10.3389/fpsyg.2014.01568

## Presentations

### Talks
Sleegers, W.W.A., Proulx, T. & Van Beest (2016). Evidence of aversive arousal motivating compensatory behavior. Presentation at ASPO conference, Leiden.

Sleegers, W.W.A., Proulx, T. & Van Beest (2015). Capturing the physiological response to meaning violations: An eye tracker approach. Colloquium presentation at Tilburg University, Tilburg.

Proulx, T. & Sleegers, W.W.A. (2014). Meaning Maintenance Model: Towards a unified account of threat-compensation behaviors. Presentation at KLI conference, Zeist.

Sleegers, W.W.A., Proulx, T., & Van Beest (2014). Cyberball and eye tracking: Support for the numbing hypothesis of social exclusion. Presentation at ASPO 2014, Groningen.

Sleegers, W.W.A., Proulx, T., & Van Beest (2014). Ostracism and eye tracking. Presentation at EASP preconference on threat regulation, Amsterdam.

### Posters
Sleegers, W.W.A., Proulx, T., & Van Beest (2016). Ostracism and eye tracking: Decreased pupillary reactivity to exclusion cues. Poster presented at the SPSP conference, San Diego.

Sleegers, W.W.A., Proulx, T., & Van Beest (2015). Meaning and misconceptions: The effect of error feedback and commitment towards misconceptions on pupil size. Poster presentation at ASPO conference, Amsterdam.

Sleegers, W.W.A., Proulx, T. & Van Beest (2015). Cyberball and eye tracking: Support for the numbing hypothesis of social exclusion. Poster presented at ICPS conference, Amsterdam.

Sleegers, W.W.A., Proulx, T, & Van Beest, I. (2014). Extremism and the response to meaning threats: Extremism reduces pupillary response to threat and increases affirmation of values. Poster 	session presented at the KLI conference, Zeist.

## Journals

### Reviewed for:
- Biological Psychology
- European Journal of Social Psychology
- PLoS ONE
- British Journal of Social Psychology

## Teaching

### Tilburg University

### Courses:

- `2015/2017` Research Master: Experimental Research and Meta-Analysis
- `2016-2017` Attitudes and Advertising
- `2016-2017` Course in R software

### Seminars:

- `2012-2017` Social Psychology
- `2015-2016` Introduction and History of Psychology
- `2014-2015` Cultural Psychology
- `2013-2015` Academic Skills
- `2012-2013` Group Skills

### Individual lectures

- `2016` Social Psychology
- `2014` Introduction and History of Psychology on intrapersonal conflict
- `2013` Introduction to Social Psychology for prospective students

### Supervision

- `2016-2017` Master in Psychology theses (7 students) 
- `2013-2017` Bachelor in Psychology theses (12 students)  
- `2012-2017` Research Skills in Psychology (7 groups of students)

### Coordination

- `2014-2017` Social Psychology
- `2016-2017` Attitudes and Advertising

### Other

### Workshops

- `2013-2017` An Introduction to R

## Activities

### Department
1. Voluntary Research Assistance program organizer.

2. Member of the internet lab committee.
		
### Faculty
Member of the Tilburg School of Social and Behavioral Sciences PhD-council from 2014 to 2016.

			
### Workshops
1. Organized a workshop on Bayesian Statistics for Behavioural Scientists by dr. E.J. Wagenmakers at Radboud University.	

2. Organized a workshop on Latent Growth Modeling using SEM by dr. Reinoud Stoel at Radboud University.
			
### Conferences	
ASPO dissertation prize committee member from 2014 to 2015. 	

## Technical skills

### Statistics
1. [R](https://www.r-project.org): A free software environment for statistical computing and graphics.	

2. [SPSS](https://www.ibm.com/analytics/us/en/technology/spss/): A proprietary data analysis program (inferior to R). 

### Programming
1. [Python](https://www.python.org): A cross-platform procedural programming language.

2. [HTML](https://www.w3.org/html/) and [CSS](https://www.w3.org/Style/CSS/Overview.en.html): Markup language for creating web pages and web applications.

### Experimental design
1. [Millisecond’s Inquisit](http://www.millisecond.com): Stimulus delivery and experimental design software.

2. [oTree](http://www.otree.org): Framework based on Python and Django to create standard and interactive online psychological experiments.

3. [Psychology Software Tool’s E-Prime](https://www.pstnet.com/eprime.cfm): Stimulus delivery and experimental design software.

4. [Tobii Studio and Tobii Studio Extensions for E-prime](http://www.tobiipro.com/product-listing/tobii-pro-studio/): software to run eye tracker experiments using Tobii eye trackers.

5. [Adobe’s Authorware](http://www.adobe.com/products/authorware/): Stimulus delivery and experimental design software. This has been discontinued, please do not make me use it.

6. [Neurobehavioural Systems’ Presentation®](https://www.neurobs.com): A stimulus delivery and experimental control program for neuroscience.

## Projects

### Website

I have my own website at [www.willemsleegers.com](www.willemsleegers.com) where I write about my research and offer tutorials on various topics related to my research, such how to prepare eye tracker data. These tutorials mostly consist of the statistical programming language R. The website itself is also created in R.

### Github

On my Github page I host several repositories of code that can be useful to fellow academics. This includes code on a mouse-tracking implementation in oTree and the analysis of multiple-choice exams.
